# Generated by Django 5.0.4 on 2024-05-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active', 'Can blocket users')]},
        ),
    ]
