# Generated by Django 5.0.4 on 2024-05-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Без темы', max_length=100, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('subject',),
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала рассылки')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='Дата окончания рассылки')),
                ('period', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('completed', 'Завершена')], default='created', max_length=20, verbose_name='Статус')),
                ('is_activated', models.BooleanField(default=True)),
                ('client', models.ManyToManyField(to='newsletter.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата последней попытки')),
                ('status', models.CharField(choices=[('successfully', 'Успешно'), ('error', 'Ошибка')], default='successfully', verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.client', verbose_name='Клиент')),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('status',),
            },
        ),
    ]
