# Generated by Django 5.0.4 on 2024-05-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_message_newsletter_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='date_last_attempt',
            new_name='last',
        ),
    ]
